#!/usr/bin/env bash


# Navigation
alias cd..="cd .."
alias cd2="cd ../.."
alias cd3="cd ../../.."
alias cd4="cd ../../../.."

# Display
alias path="echo -e '${PATH//:/\\n}'" # Print each PATH entry on a separate line
alias cls="clear"

# TERM Configuration
alias tmux="tmux -2"
alias screen="screen -U -T screen-256color"

# Typos
alias gti="git"
alias quit="exit"

# -A List all entries except . & ..
# -a Include directory entries whose names begin with a dot (.)
# -h Use unit suffixes: Byte, Kilobyte, Megabyte, Gigabyte, Terabyte and Petabyte
# -F Display '/' after directory, '*' after executable, '@' after symbolic link,
# '=' after socket, '%' after whiteout, '|' after a FIFO.
alias ls="ls -h ${LS_COLOR_FLAG} ${LS_DIRECTORY_FIRST_FLAG}"
alias l="ls -lF ${LS_COLOR_FLAG}"
alias la="ls -laF ${LS_COLOR_FLAG}"
alias lsd="ls -Al | grep '^d'"

### GUI Apps
alias finder="open -a Finder"
alias here="open -a Finder ."
alias safari="open -a Safari"
alias textedit="open -a '/System/Applications/TextEdit.app'"
alias sourcetree="open -a '/Applications/SourceTree.app'"
alias xcode="open -a '/Applications/XCode.app'"
alias ios="open -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app"
alias emacs="open -a /Applications/Emacs.app"
alias slack="open -a '/Applications/Slack.app'"

### Homebrew
alias brew_upgrade_cask="brew update;brew upgrade \$(brew outdated --greedy --verbose | grep -v '(latest)' | cut -d' ' -f1)"

### tlrc - tldr command line client
alias tlrc="tldr"

### Web services shortcuts
alias weather="curl wttr.in"

### Java version quick select (using asdf)
if command -v asdf &> /dev/null; then
  alias java_list='asdf list java'
  alias java_versions='asdf list all java | grep -E "(temurin|adoptopenjdk|openjdk).*17"'
  # Example alias:
  # alias java_11='asdf shell java temurin-11.0.21+9 && java --version'
fi
