# ~/.bash_profile:
# Sourced by the command interpreter for login shells.
# Order of sourcing: /etc/profile, ~/.bash_profile, ~/.bash_login, ~/.profile


# Source shell.environment if exist
if [ -f ~/.shell.environment ]; then
  source ~/.shell.environment
fi

# About All other things
# Source ~/.bashrc if exist (not automatically sourced in non-login shells)
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
