# ~/.zshenv
# sourced by zsh(1) always at first, used to exporte environment variables.

# Import required functions
if [ -f ~/.shellenv ]; then
  source ~/.shellenv
fi

### Configuration #############################################################
_export_language
_export_brew_shell_environment
_export_brew_packages_environment
